# ----------------------------machine dependent file
MODE = optim

# extern library and program variables
MEX 		= 	mex

# compiler and linker variable 
INCLUDES =	-I${FFTW3_DIR}/include

LIBS = 		-L${FFTW3_DIR}/lib -lfftw3 -lm

AR = ar
ARFLAGS = -r

CC  = gcc
CXX = g++

# -Wall -Wno-sign-compare 
#CFLAGS   = -g -Wall -W -Wno-sign-compare -Wno-unused-label -MMD ${INCLUDES}
#CXXFLAGS = -g -Wall -W -Wno-sign-compare -Wno-unused-label -MMD ${INCLUDES}
CFLAGS   = -fPIC -O3 -w -MMD ${INCLUDES}
CXXFLAGS = -fPIC -O3 -w -MMD ${INCLUDES}

ifeq ($(MODE),debug)
else
	CFLAGS 	+= -DNDEBUG
	CXXFLAGS += -DNDEBUG
endif

LDFLAGS = ${LIBS}

RANLIB = ranlib

# rules
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $*.cpp

%.o: %.c
	$(CC) $(CFLAGS) -c $*.c
